// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UngDungMangXaHoi.Infrastructure.Persistence;

#nullable disable

namespace UngDungMangXaHoi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Account", b =>
                {
                    b.Property<int>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("account_id"));

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("account_id");

                    b.HasIndex("account_type");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("admin_level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("moderator");

                    b.Property<string>("bio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("hometown")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_private")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("job")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("admin_id");

                    b.HasIndex("account_id")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("device_info")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("login_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("history_id");

                    b.HasIndex("account_id");

                    b.ToTable("LoginHistory", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.OTP", b =>
                {
                    b.Property<int>("otp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("otp_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("otp_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("otp_id");

                    b.HasIndex("account_id", "otp_hash");

                    b.ToTable("OTPs", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Post", b =>
                {
                    b.Property<int>("post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("post_id"));

                    b.Property<string>("caption")
                        .HasMaxLength(2200)
                        .HasColumnType("nvarchar(2200)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("is_visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("privacy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Public")
                        .HasColumnName("privacy");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.PostMedia", b =>
                {
                    b.Property<int>("media_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("media_id"));

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("media_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("media_order");

                    b.Property<string>("media_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("media_type");

                    b.Property<string>("media_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("media_url");

                    b.Property<int>("post_id")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.HasKey("media_id");

                    b.HasIndex("post_id");

                    b.ToTable("PostMedia", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("token_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("token_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("token_id");

                    b.HasIndex("account_id");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("bio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("hometown")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_private")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("job")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("user_id");

                    b.HasIndex("account_id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Account", b =>
                {
                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.Email", "email", b1 =>
                        {
                            b1.Property<int>("account_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("account_id");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[email] IS NOT NULL");

                            b1.ToTable("Accounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("account_id");
                        });

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.PasswordHash", "password_hash", b1 =>
                        {
                            b1.Property<int>("account_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("password_hash");

                            b1.HasKey("account_id");

                            b1.ToTable("Accounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("account_id");
                        });

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.PhoneNumber", "phone", b1 =>
                        {
                            b1.Property<int>("account_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("phone");

                            b1.HasKey("account_id");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[phone] IS NOT NULL");

                            b1.ToTable("Accounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("account_id");
                        });

                    b.Navigation("email");

                    b.Navigation("password_hash")
                        .IsRequired();

                    b.Navigation("phone");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Admin", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithOne("Admin")
                        .HasForeignKey("UngDungMangXaHoi.Domain.Entities.Admin", "account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.ImageUrl", "avatar_url", b1 =>
                        {
                            b1.Property<int>("admin_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("NVARCHAR(MAX)")
                                .HasColumnName("avatar_url");

                            b1.HasKey("admin_id");

                            b1.ToTable("Admins", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("admin_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("avatar_url");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.OTP", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Post", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.PostMedia", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Post", "Post")
                        .WithMany("Media")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.User", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithOne("User")
                        .HasForeignKey("UngDungMangXaHoi.Domain.Entities.User", "account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.ImageUrl", "avatar_url", b1 =>
                        {
                            b1.Property<int>("user_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("avatar_url");

                            b1.HasKey("user_id");

                            b1.ToTable("Users", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.UserName", "username", b1 =>
                        {
                            b1.Property<int>("user_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("username");

                            b1.HasKey("user_id");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("avatar_url");

                    b.Navigation("username")
                        .IsRequired();
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Account", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Post", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
