// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UngDungMangXaHoi.Infrastructure.Persistence;

#nullable disable

namespace UngDungMangXaHoi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Account", b =>
                {
                    b.Property<int>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("account_id"));

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("business_expires_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("business_verified_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("account_id");

                    b.HasIndex("account_type");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.AccountSanction", b =>
                {
                    b.Property<int>("sanction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sanction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sanction_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("action_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action_type");

                    b.Property<int?>("admin_id")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<DateTime?>("end_at")
                        .HasColumnType("datetime")
                        .HasColumnName("end_at");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("start_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("start_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("sanction_id");

                    b.HasIndex("account_id");

                    b.HasIndex("admin_id");

                    b.ToTable("AccountSanctions", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("admin_level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("moderator");

                    b.Property<string>("bio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("hometown")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_private")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("job")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("admin_id");

                    b.HasIndex("account_id")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.AdminAction", b =>
                {
                    b.Property<int>("action_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("action_id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("admin_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("target_id")
                        .HasColumnType("int");

                    b.Property<string>("target_type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("action_id");

                    b.HasIndex("admin_id");

                    b.ToTable("AdminActions", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Block", b =>
                {
                    b.Property<int>("block_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("block_id"));

                    b.Property<int>("blocked_id")
                        .HasColumnType("int");

                    b.Property<int>("blocker_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.HasKey("block_id");

                    b.HasIndex("blocked_id");

                    b.HasIndex("blocker_id", "blocked_id")
                        .IsUnique();

                    b.ToTable("Blocks", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.BusinessVerificationRequest", b =>
                {
                    b.Property<int>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("request_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int?>("assigned_admin_id")
                        .HasColumnType("int")
                        .HasColumnName("assigned_admin_id");

                    b.Property<string>("documents_url")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("documents_url");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("reviewed_at")
                        .HasColumnType("datetime")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("reviewed_notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reviewed_notes");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("submitted_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("request_id");

                    b.HasIndex("account_id");

                    b.HasIndex("assigned_admin_id");

                    b.HasIndex("status");

                    b.ToTable("BusinessVerificationRequests", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Hashtags")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("hashtags");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_edited");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int")
                        .HasColumnName("likes_count");

                    b.Property<string>("MentionedUserIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mentioned_user_ids");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_comment_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("RepliesCount")
                        .HasColumnType("int")
                        .HasColumnName("replies_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.CommentEditHistory", b =>
                {
                    b.Property<int>("CommentEditHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_edit_history_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentEditHistoryId"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("edited_at");

                    b.Property<string>("OldContent")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_content");

                    b.HasKey("CommentEditHistoryId");

                    b.HasIndex("CommentId");

                    b.HasIndex("EditedAt");

                    b.ToTable("CommentEditHistories", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.CommentMention", b =>
                {
                    b.Property<int>("CommentMentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_mention_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentMentionId"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasColumnName("length");

                    b.Property<int>("MentionedAccountId")
                        .HasColumnType("int")
                        .HasColumnName("mentioned_account_id");

                    b.Property<int>("StartPosition")
                        .HasColumnType("int")
                        .HasColumnName("start_position");

                    b.HasKey("CommentMentionId");

                    b.HasIndex("CommentId");

                    b.HasIndex("MentionedAccountId");

                    b.ToTable("CommentMentions", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.CommentReaction", b =>
                {
                    b.Property<int>("CommentReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_reaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentReactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("reaction_type");

                    b.HasKey("CommentReactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CommentId");

                    b.HasIndex("CommentId", "AccountId")
                        .IsUnique();

                    b.ToTable("CommentReactions", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.ContentModeration", b =>
                {
                    b.Property<int>("ModerationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModerationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModerationID"));

                    b.Property<double>("AIConfidence")
                        .HasColumnType("float");

                    b.Property<int>("ContentID")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToxicLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("accountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int?>("commentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<int?>("postId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.HasKey("ModerationID");

                    b.HasIndex("accountId");

                    b.HasIndex("commentId");

                    b.HasIndex("postId");

                    b.ToTable("ContentModeration", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.ContentReport", b =>
                {
                    b.Property<int>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("report_id"));

                    b.Property<int?>("assigned_admin_id")
                        .HasColumnType("int");

                    b.Property<int>("content_id")
                        .HasColumnType("int");

                    b.Property<string>("content_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("handled_at")
                        .HasColumnType("datetime");

                    b.Property<string>("handled_notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("reporter_account_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("report_id");

                    b.HasIndex("assigned_admin_id");

                    b.HasIndex("reporter_account_id");

                    b.HasIndex("status");

                    b.ToTable("ContentReports", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("conversation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("conversation_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user1_id")
                        .HasColumnType("int");

                    b.Property<int>("user2_id")
                        .HasColumnType("int");

                    b.HasKey("conversation_id");

                    b.HasIndex("user2_id");

                    b.HasIndex("user1_id", "user2_id")
                        .IsUnique();

                    b.ToTable("ConversationsNew", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("follow_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("follow_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int>("follower_id")
                        .HasColumnType("int");

                    b.Property<int>("following_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("follow_id");

                    b.ToTable("Follows", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupConversation", b =>
                {
                    b.Property<int>("conversation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("conversation_id"));

                    b.Property<string>("avatar_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("invite_permission")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("all");

                    b.Property<bool>("is_group")
                        .HasColumnType("bit");

                    b.Property<int?>("max_members")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("conversation_id");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupConversationMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("conversation_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("last_read_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("last_read_message_id")
                        .HasColumnType("int");

                    b.Property<string>("role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("member");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.HasIndex("conversation_id", "user_id")
                        .IsUnique();

                    b.ToTable("ConversationMembers", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupMessage", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("message_id"));

                    b.Property<string>("content")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<int>("conversation_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("file_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("media_url");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("is_pinned")
                        .HasColumnType("bit");

                    b.Property<string>("message_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("pinned_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("pinned_by")
                        .HasColumnType("int");

                    b.Property<string>("reactions")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("read_by")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int?>("reply_to_message_id")
                        .HasColumnType("int")
                        .HasColumnName("reply_to");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.HasKey("message_id");

                    b.HasIndex("conversation_id");

                    b.HasIndex("reply_to_message_id");

                    b.HasIndex("user_id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupMessageReaction", b =>
                {
                    b.Property<int>("message_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("reaction_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("message_id", "user_id");

                    b.ToTable("GroupMessageReactions");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupMessageRead", b =>
                {
                    b.Property<int>("message_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("read_at")
                        .HasColumnType("datetime2");

                    b.HasKey("message_id", "user_id");

                    b.ToTable("GroupMessageReads");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupMessageRestriction", b =>
                {
                    b.Property<int>("restriction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("restriction_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int>("restricted_user_id")
                        .HasColumnType("int");

                    b.Property<int>("restricting_user_id")
                        .HasColumnType("int");

                    b.HasKey("restriction_id");

                    b.HasIndex("restricted_user_id");

                    b.HasIndex("restricting_user_id", "restricted_user_id")
                        .IsUnique();

                    b.ToTable("MessageRestrictions", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("history_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("device_info")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("login_time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("history_id");

                    b.HasIndex("account_id");

                    b.ToTable("LoginHistory", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Message", b =>
                {
                    b.Property<int>("message_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("message_id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("conversation_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("is_recalled")
                        .HasColumnType("bit");

                    b.Property<string>("media_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("message_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("read_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("sender_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("thumbnail_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("message_id");

                    b.HasIndex("conversation_id");

                    b.HasIndex("created_at");

                    b.HasIndex("sender_id");

                    b.ToTable("MessagesNew", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.ModerationLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<DateTime>("ActionAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("ModerationID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LogID");

                    b.HasIndex("AdminID");

                    b.HasIndex("ModerationID");

                    b.ToTable("ModerationLogs", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notification_id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("is_read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int?>("post_id")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int?>("sender_id")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<int>("type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("notification_id");

                    b.HasIndex("post_id");

                    b.HasIndex("sender_id");

                    b.HasIndex("user_id", "is_read", "created_at")
                        .HasDatabaseName("IX_Notification_UserId_IsRead_CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.OTP", b =>
                {
                    b.Property<int>("otp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("otp_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("otp_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("otp_id");

                    b.HasIndex("account_id", "otp_hash");

                    b.ToTable("OTPs", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Post", b =>
                {
                    b.Property<int>("post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("post_id"));

                    b.Property<string>("MentionedUserIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("mentioned_user_ids");

                    b.Property<string>("TaggedUserIds")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("tagged_user_ids");

                    b.Property<string>("caption")
                        .HasMaxLength(2200)
                        .HasColumnType("nvarchar(2200)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("is_visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("privacy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Public")
                        .HasColumnName("privacy");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.PostMedia", b =>
                {
                    b.Property<int>("media_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("media_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("media_order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("media_order");

                    b.Property<string>("media_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("media_type");

                    b.Property<string>("media_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("media_url");

                    b.Property<int>("post_id")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.HasKey("media_id");

                    b.HasIndex("post_id");

                    b.ToTable("PostMedia", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Reaction", b =>
                {
                    b.Property<int>("reaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reaction_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("post_id")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("reaction_type")
                        .HasColumnType("int")
                        .HasColumnName("reaction_type");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("reaction_id");

                    b.HasIndex("user_id");

                    b.HasIndex("post_id", "user_id")
                        .IsUnique()
                        .HasDatabaseName("UQ_Reaction_Post_User");

                    b.ToTable("Reactions", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("token_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("token_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("token_id");

                    b.HasIndex("account_id");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Share", b =>
                {
                    b.Property<int>("share_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("share_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("share_id"));

                    b.Property<string>("caption")
                        .HasMaxLength(2200)
                        .HasColumnType("nvarchar(2200)")
                        .HasColumnName("caption");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("post_id")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<string>("privacy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("public")
                        .HasColumnName("privacy");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("share_id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("Shares", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Story", b =>
                {
                    b.Property<int>("story_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("story_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("story_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("media_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("media_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("media_url");

                    b.Property<string>("privacy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("privacy");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("story_id");

                    b.HasIndex("user_id");

                    b.ToTable("Stories", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.StoryView", b =>
                {
                    b.Property<int>("view_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("view_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("view_id"));

                    b.Property<int>("story_id")
                        .HasColumnType("int")
                        .HasColumnName("story_id");

                    b.Property<DateTime>("viewed_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("viewed_at");

                    b.Property<int>("viewer_id")
                        .HasColumnType("int")
                        .HasColumnName("viewer_id");

                    b.HasKey("view_id");

                    b.HasIndex("viewer_id");

                    b.HasIndex("story_id", "viewer_id")
                        .IsUnique()
                        .HasDatabaseName("UQ_StoryViews");

                    b.ToTable("StoryViews", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<int>("account_id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("bio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("date");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("hometown")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_private")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("job")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("last_seen")
                        .HasColumnType("datetime2");

                    b.Property<string>("website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("user_id");

                    b.HasIndex("account_id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Account", b =>
                {
                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.Email", "email", b1 =>
                        {
                            b1.Property<int>("account_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("email");

                            b1.HasKey("account_id");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[email] IS NOT NULL");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("account_id");
                        });

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.PasswordHash", "password_hash", b1 =>
                        {
                            b1.Property<int>("account_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("password_hash");

                            b1.HasKey("account_id");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("account_id");
                        });

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.PhoneNumber", "phone", b1 =>
                        {
                            b1.Property<int>("account_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("phone");

                            b1.HasKey("account_id");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[phone] IS NOT NULL");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("account_id");
                        });

                    b.Navigation("email");

                    b.Navigation("password_hash")
                        .IsRequired();

                    b.Navigation("phone");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.AccountSanction", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany("AccountSanctions")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Admin", "Admin")
                        .WithMany("AccountSanctions")
                        .HasForeignKey("admin_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Admin", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithOne("Admin")
                        .HasForeignKey("UngDungMangXaHoi.Domain.Entities.Admin", "account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.ImageUrl", "avatar_url", b1 =>
                        {
                            b1.Property<int>("admin_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("NVARCHAR(MAX)")
                                .HasColumnName("avatar_url");

                            b1.HasKey("admin_id");

                            b1.ToTable("Admins");

                            b1.WithOwner()
                                .HasForeignKey("admin_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("avatar_url");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.AdminAction", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Admin", "Admin")
                        .WithMany("AdminActions")
                        .HasForeignKey("admin_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Block", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "Blocked")
                        .WithMany()
                        .HasForeignKey("blocked_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "Blocker")
                        .WithMany()
                        .HasForeignKey("blocker_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.BusinessVerificationRequest", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Accounts")
                        .WithMany("BusinessVerificationRequests")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Admin", "AssignedAdmin")
                        .WithMany("BusinessVerificationRequestsReviewed")
                        .HasForeignKey("assigned_admin_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Accounts");

                    b.Navigation("AssignedAdmin");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Comment", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.CommentEditHistory", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Comment", "Comment")
                        .WithMany("EditHistory")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.CommentMention", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Comment", "Comment")
                        .WithMany("Mentions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "MentionedAccount")
                        .WithMany()
                        .HasForeignKey("MentionedAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("MentionedAccount");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.CommentReaction", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.ContentModeration", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany("ContentModerations")
                        .HasForeignKey("accountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Comment", "Comment")
                        .WithMany("ContentModerations")
                        .HasForeignKey("commentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Post", "Post")
                        .WithMany("ContentModerations")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Comment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.ContentReport", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Admin", "AssignedAdmin")
                        .WithMany("ContentReports")
                        .HasForeignKey("assigned_admin_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "ReporterAccount")
                        .WithMany("ContentReports")
                        .HasForeignKey("reporter_account_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAdmin");

                    b.Navigation("ReporterAccount");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("user1_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("user2_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupConversationMember", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.GroupConversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("conversation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupMessage", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.GroupConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("conversation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.GroupMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("reply_to_message_id");

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupMessageRestriction", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "RestrictedUser")
                        .WithMany()
                        .HasForeignKey("restricted_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "RestrictingUser")
                        .WithMany()
                        .HasForeignKey("restricting_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RestrictedUser");

                    b.Navigation("RestrictingUser");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Message", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("conversation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.ModerationLog", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Admin", "Admin")
                        .WithMany("ModerationLogs")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.ContentModeration", "ContentModeration")
                        .WithMany("ModerationLogs")
                        .HasForeignKey("ModerationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("ContentModeration");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Notification", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("sender_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Sender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.OTP", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Post", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.PostMedia", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Post", "Post")
                        .WithMany("Media")
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Reaction", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Share", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Story", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.StoryView", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Story", "Story")
                        .WithMany("Views")
                        .HasForeignKey("story_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungMangXaHoi.Domain.Entities.User", "Viewer")
                        .WithMany()
                        .HasForeignKey("viewer_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.User", b =>
                {
                    b.HasOne("UngDungMangXaHoi.Domain.Entities.Account", "Account")
                        .WithOne("User")
                        .HasForeignKey("UngDungMangXaHoi.Domain.Entities.User", "account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.ImageUrl", "avatar_url", b1 =>
                        {
                            b1.Property<int>("user_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("avatar_url");

                            b1.HasKey("user_id");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.OwnsOne("UngDungMangXaHoi.Domain.ValueObjects.UserName", "username", b1 =>
                        {
                            b1.Property<int>("user_id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("username");

                            b1.HasKey("user_id");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("Account");

                    b.Navigation("avatar_url");

                    b.Navigation("username")
                        .IsRequired();
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountSanctions");

                    b.Navigation("Admin");

                    b.Navigation("BusinessVerificationRequests");

                    b.Navigation("ContentModerations");

                    b.Navigation("ContentReports");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Admin", b =>
                {
                    b.Navigation("AccountSanctions");

                    b.Navigation("AdminActions");

                    b.Navigation("BusinessVerificationRequestsReviewed");

                    b.Navigation("ContentReports");

                    b.Navigation("ModerationLogs");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Comment", b =>
                {
                    b.Navigation("ContentModerations");

                    b.Navigation("EditHistory");

                    b.Navigation("Mentions");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.ContentModeration", b =>
                {
                    b.Navigation("ModerationLogs");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupConversation", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.GroupMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ContentModerations");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("UngDungMangXaHoi.Domain.Entities.Story", b =>
                {
                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
