using System;
using System.Collections.Generic;

namespace UngDungMangXaHoi.Application.DTOs
{
    /// <summary>
    /// DTO cho việc gửi message trong GROUP CHAT
    /// </summary>
    public class SendGroupMessageDto
    {
        public int ConversationId { get; set; }
        public int UserId { get; set; }
        public string? Content { get; set; } // Hỗ trợ text, số, mixed
        public string MessageType { get; set; } = "text"; // text, image, video, file
        public string? FileUrl { get; set; }
        public int? ReplyToMessageId { get; set; } // Cho threaded chat
        // Optional ID generated by client for optimistic UI. Server will echo this back in broadcasts
        // so client can reconcile/remove temporary messages if save fails.
        public string? ClientTempId { get; set; }
    }

    /// <summary>
    /// DTO response cho message (bao gồm thông tin user)
    /// </summary>
    public class GroupMessageDto
    {
        public int MessageId { get; set; }
        public int ConversationId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; } = string.Empty;
        public string? UserAvatar { get; set; }
        public string? Content { get; set; }
        public string MessageType { get; set; } = "text";
        public string? FileUrl { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public bool IsDeleted { get; set; }
        
        // Reply info (nếu message này reply message khác)
        public GroupMessageReplyDto? ReplyTo { get; set; }
        
        // Reactions
        public Dictionary<string, List<int>>? Reactions { get; set; } // {"❤️": [1,2], "😂": [3]}
        
        // Read receipts
        public List<ReadReceiptDto>? ReadBy { get; set; }
        // Whether the current requesting user has read this message
        public bool IsReadByMe { get; set; }
    }

    /// <summary>
    /// DTO cho reply message (simplified)
    /// </summary>
    public class GroupMessageReplyDto
    {
        public int MessageId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; } = string.Empty;
        public string? Content { get; set; }
        public string MessageType { get; set; } = "text";
        public string? FileUrl { get; set; }
    }

    /// <summary>
    /// DTO cho read receipt
    /// </summary>
    public class ReadReceiptDto
    {
        public int UserId { get; set; }
        public DateTime ReadAt { get; set; }
    }

    /// <summary>
    /// DTO cho paginated messages response
    /// </summary>
    public class PaginatedGroupMessagesDto
    {
        public List<GroupMessageDto> Messages { get; set; } = new List<GroupMessageDto>();
        public int TotalCount { get; set; }
        public int Page { get; set; }
        public int PageSize { get; set; }
        public bool HasMore { get; set; }
    }

    /// <summary>
    /// DTO cho reaction request
    /// </summary>
    public class AddReactionDto
    {
        public int MessageId { get; set; }
        public int UserId { get; set; }
        public string Emoji { get; set; } = string.Empty; // ❤️, 😂, 👍, etc.
    }
}
